name: BlockWars
version: '${project.version}'
main: org.gomadango0113.blockwars.BlockWars

commands:
  blockwars_start:
    description: ゲームを開始させるコマンド
    permission: blockwars.command.game_start
  blockwars_shop:
    description: ショップに関するコマンド
    permission: blockwars.command.shop
  blockwars_teamupdate:
    description: チームアップデートに関するコマンド
    permission: blockwars.command.teamupdate
